# Site settings
title: The Bayesian Observer
email: 
description: "A blog on technology and economics."
baseurl: ""
url: "http://bayesian observer.github.io"
twitter_username: bayesianobserver
github_username:  bayesianobserver

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
